### ISSUE TITLE
Rebooting rless

### ISSUE THREAD

**Issue by AMythicDev** [arijit79/rless#1]
Hi @Takashiidobe I am the author of [minus](https://github.com/arijit79/minus). In all these years, minus has been a library for applications to integrate and that's what it will remain for its lifetime. But people want to minus just like `less` rather than relying on the mercy of application integrating minus as a dependency.

I see you had put an effort to bring minus as a system pager like `less` and although it's in no way a completely ready for daily use, it could be a great replacement for something like `less`.

Hence I am willing to takeover it from you and develop it further. The most important reason I want to takeover is that it wouldn't create useless name pollution inside crates.io while still giving a good name to a project.

So if you want to give the ownership to me, please do the following:-
- Give either complete ownership of the project or maintainer rights on GitHub.
- Give all permissions on crates.io for the project.

**Comment by Takashiidobe** [comment]
All yours, I've given you ownership of this repo on github and given you ownership of the crates.io project. 
Have fun with the project.

**Comment by AMythicDev** [comment]
Thanks @Takashiidobe. I will start doing stuff on it after I get free with a minor release of minus.
